blog/urls.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd party:
from django.urls import path
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal:
from . import views
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# Urls for the blog which shows all posts and post expand which
# enters the post for the user to read
urlpatterns = [
    path('blog/', views.PublishedPosts.as_view(), name='blog'),
    path('<slug:slug>/', views.PostExpand.as_view(), name='post_expand'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('add/', views.add_product, name='add_product'),
    path(
        'delete/<int:product_id>/',
        views.delete_product,
        name='delete_product'
    ),
    path('edit/<int:product_id>/', views.edit_product, name='edit_product'),
]

throttles_motocross/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('', include('contact.urls')),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = 'throttles_motocross.views.handler404'

checkout/models.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd Party
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
# Internal
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from products.models import Product
from profiles.models import UserProfile
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class Order(models.Model):
    order_number = models.CharField(
        max_length=35,
        null=False,
        editable=False,
        default=''
    )
    user_profile = models.ForeignKey(
        UserProfile,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='orders'
        )
    full_name = models.CharField(
        max_length=55,
        null=False,
        blank=False,
        default=''
    )
    email = models.EmailField(
        max_length=254,
        null=False,
        blank=False,
        default=''
    )
    phone_number = models.CharField(
        max_length=20,
        null=False,
        blank=False,
        default=''
    )
    address1 = models.CharField(
        max_length=85,
        null=False,
        blank=False,
        default=''
    )
    address2 = models.CharField(
        max_length=85,
        null=True,
        blank=True,
        default=''
    )
    town_or_city = models.CharField(
        max_length=45,
        null=False,
        blank=False,
        default=''
    )
    postcode = models.CharField(
        max_length=25,
        null=True,
        blank=True,
        default=''
    )
    county = models.CharField(
        max_length=85,
        null=True,
        blank=True,
        default=''
    )
    country = CountryField(
        blank_label='Country *',
        null=False,
        blank=False,
    )
    date = models.DateTimeField(
        auto_now_add=True,
        null=True
        )
    delivery_cost = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        default=0
    )
    order_total = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        null=False,
        default=0
    )
    grand_total = models.DecimalField(
        max_digits=10,
        decimal_places=3,
        null=False,
        default=0
    )
    original_cart = models.TextField(
        null=False,
        blank=False,
        default=''
    )
    stripe_pid = models.CharField(
        max_length=254,
        null=False,
        blank=False,
        default='')

    def _generate_order_number(self):
        """
        Generate a random, unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand total each time a line item is added
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100
                )
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """
    A model for a web order line item
    """
    order = models.ForeignKey(
        Order,
        null=False,
        blank=False,
        on_delete=models.CASCADE,
        related_name='lineitems'
        )
    product = models.ForeignKey(
        Product,
        null=False,
        blank=False,
        on_delete=models.CASCADE
        )
    product_size = models.CharField(
        max_length=2,
        null=True,
        blank=True
        )
    quantity = models.IntegerField(
        null=False,
        blank=False,
        default=0
        )
    lineitem_total = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        null=False,
        blank=False,
        editable=False
        )

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.code} on order {self.order.order_number}'

products/models.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd Party
from django.db import models
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class Category(models.Model):

    class Meta:
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(
        max_length=254,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    def get_friendly_name(self):
        return self.friendly_name


class Product(models.Model):
    category = models.ForeignKey(
        'Category', null=True, blank=True, on_delete=models.SET_NULL)
    sku = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254)
    description = models.TextField()
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    brand = models.CharField(
        max_length=50,
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

products/forms.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd Party
from django import forms
# Internal
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from .models import Product, Category
from .widgets import CustClearableFileInput
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

        widgets = {
            'image': forms.ClearableFileInput(attrs={'label': 'Image'}),
        }

    image = forms.ImageField(
        label='Image',
        required=False,
        widget=CustClearableFileInput
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        categories_list = Category.objects.all()
        friendly_names = [
            (c.id, c.get_friendly_name()) for c in categories_list
        ]
        self.fields['category'].label = 'Category'
        self.fields['category'].choices = friendly_names
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'border-secondary rounded'

products/views.py
# Imports
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# 3rd Party
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Internal
from .models import Product, Category
from .forms import ProductForm
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


def all_products(request):
    """ A view to return the all product page """

    products = Product.objects.all()
    categories_list = Category.objects.all()

    query = None
    categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=categories)
            categories = Category.objects.filter(name__in=categories)

    if request.GET:
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please input search criteria")
                return redirect(reverse('products'))

            queries = Q(name__icontains=query) | Q(
                description__icontains=query)
            products = products.filter(queries)

    current_sort = f'{sort}_{direction}'

    context = {
        'products': products,
        'search_term': query,
        'categories_list': categories_list,
        'current_sort': current_sort,
    }

    return render(request, 'products/product_list.html', context)


def product_detail(request, product_id):
    """ A view to return the all product page """

    product = get_object_or_404(Product, pk=product_id)
    categories_list = Category.objects.all()
    categories = Category.objects.all()

    context = {
        'product': product,
        'categories': categories,
        'categories_list': categories_list,
    }

    context = {
        'product': product,
    }

    return render(request, 'products/product_detail.html', context)


@login_required
def add_product(request):
    """
    Add a product to the shop
    """
    categories_list = Category.objects.all()

    if not request.user.is_superuser:
        messages.error(request, 'Only Admins can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Successfully added product to shop.')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request,
                'Failed to add product. Please check form is valid.'
            )
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
        'categories_list': categories_list,
    }

    return render(request, template, context)


@login_required
def delete_product(request, product_id):
    """
    Delete product from the shop
    """
    if not request.user.is_superuser:
        messages.error(request, 'Only Admins owners can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    messages.success(request, 'Product has been deleted.')

    return redirect(reverse('products'))


@login_required
def edit_product(request, product_id):
    """
    Edit product in the store
    """

    categories_list = Category.objects.all()

    if not request.user.is_superuser:
        messages.error(request, 'Only Admins can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product has been updated.')
            return redirect(reverse('product_detail', args=[product.id]))
        else:
            messages.error(
                request, 'Failed to update product. Check form is valid.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f'You are editing {product.name}')

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
        'categories_list': categories_list,
    }

    return render(request, template, context)

products/templates/products/add_product.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tools %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row my-5 mt-5">
        <div class="col bg-blue rounded shadow">
            <div class="col">
                <h1 class="my-5 heading-text">
                    Management- Add Product
                </h1>
            </div>
        </div>
    </div>
    <div class="row bg-light p-3 rounded my-5 shadow">
        <div class="col-12 col-md-6">
            <form action="{% url 'add_product' %}" method="POST" class="form mb-2" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field | as_crispy_field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <button class="btn btn-info rounded" type="submit">Add Product</button>
                    <a href="{% url 'products' %}" class="btn btn-outline-dark rounded">Cancel</a>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <ul class="col-sm-12 text-center">
            <li class="col-2  m-2 boot-icon list-inline-item"></li>
            <li class="col-2  m-2 helmet-icon list-inline-item"></li>
            <li class="col-2  m-2 goggle-icon list-inline-item"></li>
            <li class="col-2  m-2 boot-icon list-inline-item"></li>
            <li class="col-2  m-2 helmet-icon list-inline-item"></li>
            <li class="col-2  m-2 goggle-icon list-inline-item"></li>
        </ul>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $('#new-image').change(function () {
        var file = $('#new-image')[0].files[0];
        $('#filename').text(`Image will be set to: ${file.name}`);
    });
</script>
{% endblock %}

products/templates/products/edit_product.html
{% extends 'base.html' %}
{% load static %}
{% load cart_tools %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block extracss %}
<link rel="stylesheet" href="{% static 'checkout/css/checkout.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row my-5 mt-5 rounded shadow">
        <div class="col bg-blue rounded">
            <div class="col">
                <h1 class="my-5 heading-text">
                    Management- Edit Product
                </h1>
            </div>
        </div>
    </div>
    <div class="row bg-light p-3  my-5 rounded shadow">
        <div class="col-12 col-md-6">
            <form action="{% url 'edit_product' product.id %}" method="POST" class="form mb-2"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'image' %}
                {{ field | as_crispy_field }}
                {% else %}
                {{ field.label_tag }}
                {{ field }}
                {% endif %}
                {% endfor %}
                <div class="text-right">
                    <a href="{% url 'products' %}" class="btn btn-outline-dark rounded">Cancel</a>
                    <button class="btn btn-info rounded" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <ul class="col-sm-12 text-center">
            <li class="col-2  m-2 boot-icon list-inline-item"></li>
            <li class="col-2  m-2 helmet-icon list-inline-item"></li>
            <li class="col-2  m-2 goggle-icon list-inline-item"></li>
            <li class="col-2  m-2 boot-icon list-inline-item"></li>
            <li class="col-2  m-2 helmet-icon list-inline-item"></li>
            <li class="col-2  m-2 goggle-icon list-inline-item"></li>
        </ul>
    </div>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Popup modal for delete product button to confirm deletion -->
<div class="popupOverlay">
    <div class="popupContent">
        <h1 class="text-info">Delete Product</h1>
        <p>Are you sure?</p>
        <a class='btn btn-sm btn-danger m-2' href="{% url 'delete_product' product.id %}">Delete</a>
        <a href="#" class="btn btn-sm close btn-outline-dark m-2">Cancel</a>
    </div>
</div>
<div class="container">
    <div class="row my-5 mt-5">
        <div class="col bg-blue rounded mt-5 shadow">
            <div class="col">
                <a class=" text-decoration-none" href="{% url 'products' %}">
                    <h1 class="my-5 text-center heading-text">
                        SHOP
                    </h1>
                </a>
                <h2 class="bg-warning rounded p-1 shadow f-fam my-5" style="text-align: center;">Free Shipping on
                    orders over {{ free_delivery_threshold }}sek</h2>
            </div>
        </div>
    </div>
    <div class="row bg-light p-3 rounded my-5 shadow">
        <div class="d-none d-lg-block col-md-2">
            <h2 class="fs-6 text-info f-fam">CATEGORIES</h2>
            <hr>
            <p><a class="nav-link text-info" href="{% url 'products' %}">All Products</a></p>
            {% for category in categories_list %}
            <p><a class="nav-link text-info" href="{% url 'products' %}?category={{category.name}}">{{ category.friendly_name }}</a></p>
            {% endfor %}
            <h2 class="fs-6 text-info f-fam">All Products</h2>
            <hr>
            <p><a href="{% url 'products' %}?sort=price&direction=asc"
                    class="nav-link text-decoration-none text-info">By
                    Price</a></p>
            <p><a href="{% url 'products' %}?sort=category&direction=asc"
                    class="nav-link text-decoration-none text-info">By
                    Category</a></p>
            <p><a href="{% url 'products' %}?sort=brand&direction=desc"
                    class="nav-link text-decoration-none text-info">By
                    Brand</a></p>
            <p><a href="{% url 'products' %}?sort=rating&direction=desc"
                    class="nav-link text-decoration-none text-info">By
                    Rating</a></p>
        </div>
        <div class="col-12 col-md-6 col-lg-4 offset-lg-2 mt-5">
            <div class="image-container my-4">
                {% if product.image %}
                <a href="{{ product.image.url }}" target="_blank"><img class="card-img-top"
                        src="{{ product.image.url }}" alt="Card image cap"></a>
                {% else %}
                <a href="{}"><img class="card-img-top" src="{% static 'img/default-image.jpg' %}"
                        alt="Card image cap"></a>
                {% endif %}
            </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4 mt-5">
            <div class="mb-5 mt-md-5">
                <span class="fs-6 text-info">{{ product.brand }}</span>
                <p>{{ product.name }}</p>
                <p class="lead text-left font-weight-bold">{{ product.price }}sek{% if product.rating %}
                    <small class="text-muted"><i class="text-warning fas fa-star mr-1"></i>{{ product.rating }} /
                        5</small>
                    {% endif %}
                </p>
                <p class="text-info">{{ product.category.friendly_name }}</p>
                <p class="mt-4">{{ product.description }}</p>
                <form class="form" action="{% url 'add_to_cart' product.id %}" method="POST">
                    {% csrf_token %}
                    <div class="form-row">
                        {% with product.has_sizes as s %}
                        {% if s %}
                        <div class="col-12">
                            <label for="id_product_size">Size</label>
                            <select class="form-control rounded w-50" name="product_size" id='id_product_size'>
                                <option value="xs">XS</option>
                                <option value="s">S</option>
                                <option value="m" selected>M</option>
                                <option value="l">L</option>
                                <option value="xl">XL</option>
                            </select>
                        </div>
                        {% endif %}
                        <div class="col-12">
                            <p class="mt-3"><strong>Quantity:</strong></p>
                            <div class="form-group w-50">
                                <div class="input-group input-group-{{ product.id }}">
                                    <div class="input-group-prepend">
                                        <button
                                            class="decrement-qty btn btn-sm btn-danger rounded decrement-qty_{{ product.id }}"
                                            data-item_id="{{ product.id }}">
                                            <span>-</span>
                                        </button>
                                    </div>
                                </div>
                                    <input class="form-control qty_input rounded h-100 w-75 id_qty_{{ product.id }}"
                                        type="number" name="quantity" value="1" min="1" data-max="{{ product.stock }}"
                                        data-item_id="{{ product.id }}" aria-label="add to cart">
                                    <div class="input-group-append">
                                        <button
                                            class="increment-qty btn btn-sm btn-info rounded increment-qty_{{ product.id }}"
                                            data-item_id="{{ product.id }}">
                                            <span>+</span>
                                        </button>
                                    </div>
                                    {% if request.user.is_superuser %}
                                    <small class="my-5">
                                        <a href="#" class="btn open btn-danger">Delete</a>
                                        <a class="btn btn-outline-info"
                                            href="{% url 'edit_product' product.id %}">Edit</a>
                                    </small>
                                </div>
                            </div>
                            {% endif %}
                    </div>
                    </div>
                        <div class="col{% if s %}-12 mt-2{% endif %}">
                            <a href="{% url 'products' %}" class="btn btn-outline-secondary rounded mt-5">
                                <span>
                                    <i class="fas fa-arrow-left"></i>
                                </span>
                                <span class="text-uppercase">Return</span>
                            </a>
                            <input type="submit" class="btn text-uppercase btn-info rounded mt-5" value="Add to Cart">
                        </div>
                        <input type="hidden" name="redirect_url" value="{{ request.path }}">
                        {% endwith %}
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <ul class="col-sm-12 text-center">
            <li class="col-2  m-2 boot-icon list-inline-item"></li>
            <li class="col-2  m-2 helmet-icon list-inline-item"></li>
            <li class="col-2  m-2 goggle-icon list-inline-item"></li>
            <li class="col-2  m-2 boot-icon list-inline-item"></li>
            <li class="col-2  m-2 helmet-icon list-inline-item"></li>
            <li class="col-2  m-2 goggle-icon list-inline-item"></li>
        </ul>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<script>
    $(document).ready(function () {
        $('.open').click(function () {
            $('.popupOverlay, .popupContent').addClass('active');
        });
        $('.close, .popupOverlay').click(function () {
            $('.popupOverlay, .popupContent').removeClass('active');
        });
    });
</script>
<script>
    $(document).ready(function () {
        const incrementButtons = $('.increment-qty');
        incrementButtons.each(function () {
            $(this).on('click', function () {
                let productId = $(this).data('item_id');
                let quantityInput = $('.id_qty_' + productId);
                let maxStock = quantityInput.data('max');
                let currentValue = parseInt(quantityInput.val());
                if (currentValue < maxStock) {
                    quantityInput.val(currentValue + 1);
                }
                if (currentValue + 1 >= maxStock) {
                    $(this).prop('disabled', true);
                }
            });
        });
    });
</script>
{% include 'products/includes/quantity_script.html' %}
{% endblock %}